### PR TITLE
fix: expose the module error which is under node_modules

### LINKED ISSUE #376: How to expose node_modules package
### Discussed in https://github.com/originjs/vite-plugin-federation/discussions/375

<div type='discussions-op-text'>

<sup>Originally posted by **KayneWang** March 24, 2023</sup>
How should I expose the node_modules package like webpack example:

```javascript
exposes: {
    './vue2': './node_modules/vue/dist/vue',
},
```

I have tried these code, but it did't work:

```javascript
exposes: {
    './vue3': {
        // import: 'vue' // didnt work
        // import: 'node_modules/vue' // didnt work
    }
    // or just like this
    './vue3': 'node_modules/vue' // didnt work either
}
```</div>

### PR DESCRIPTION
**Pull request by ruleeeer**
fix #376

### CODE REVIEW

**Review by ygj6 — APPROVED** [review]

File: packages/lib/src/prod/remote-production.ts [hunk 1]
```diff
@@ -199,18 +199,9 @@ export function prodRemotePlugin(
       if (builderInfo.isRemote) {
         for (const expose of parsedOptions.prodExpose) {
           if (!expose[1].emitFile) {
-            if (!expose[1].id) {
-              // resolved the moduleId here for the reference somewhere else like #152
-              expose[1].id = (await this.resolve(expose[1].import))?.id
-              if (!expose[1].id) {
-                this.error(
```
Comment (ygj6) [inline packages/lib/src/prod/remote-production.ts:206]: I thik this error tips should be kept. See this issue #153

Comment (ruleeeer) [reply packages/lib/src/prod/remote-production.ts:206]: I tried to modify an incorrect exposure url. It seems that the prompt message of rollup can explain the problem.
image

image

Comment (ruleeeer) [reply packages/lib/src/prod/remote-production.ts:206]: I also tried the rollup prompt, which is enough to explain the problem.
image
