### PR TITLE
fix: vite 2.9.0 causes manualChunks failed

### LINKED ISSUE #178: Invalid VNode type: Symbol() error
```
<template> 
<div>
    **whats is this**
    <h1>Hello from exposed This is the HelloWorld vue from remote</h1> 
</div>
</template>
```
remote component from a host app some elements "whats is this" text is missing and the following error is on console
runtime-core.esm-bundler.js:38 [Vue warn]: Invalid VNode type: Symbol() (symbol) 

image

but if the remote is run independently txt "what's is this" is properly rendered n no errors

image

### PR DESCRIPTION
**Pull request by ruleeeer**
vite 2.9.0 updated the default `manualChunks` behavior, which caused the plugin to potentially cause shared processing to fail when used with vite 2.9.0 and above, this PR fixes the issue at vite 2.9.0 and above
<br>

image

close #178

### CODE REVIEW

File: packages/lib/src/prod/shared-production.ts [hunk 1]
```diff
@@ -454,33 +463,58 @@ export function prodSharedPlugin(
...
-            )
-            return find ? find[0] : target(argArray[0], argArray[1])
+            const result = manualChunkFunc(argArray[0], argArray[1])
+            return result ? result : target(argArray[0], argArray[1])
           }
         })
       }
 
+      // The default manualChunk function is no longer available from vite 2.9.0
+      if (typeof outputOption.manualChunks === 'undefined') {
```
Comment (flyfishzy) [inline packages/lib/src/prod/shared-production.ts:486]: Why not use `outputOption.manualChunks === undefined` ?

Comment (ruleeeer) [reply packages/lib/src/prod/shared-production.ts]: done

**Review by flyfishzy — APPROVED** [review]
